// Generated by dts-bundle-generator v9.2.4

export type GeneratedPuzzle = {
  puzzle: number[][];
  solution: string[][];
};
/**
 * Generates a random hashi puzzle.
 * @param rows Number of rows.
 * @param columns Number of columns.
 * @param numberOfIslands Number of islands in the puzzle.
 * @param doubleBridges Percentage of double bridges in the generated puzzle.
 * The value must be between 0 and 1.
 * @returns Returns the puzzle as a two-dimensional array.
 */
export declare const generate: (
  rows: number,
  columns: number,
  numberOfIslands: number,
  doubleBridges?: number,
) => GeneratedPuzzle;

export {};
